"""
Ninoclaw Setup Wizard — clean single-flow interactive CLI
"""
import os, sys, getpass

_IS_WIN = sys.platform == "win32"
if _IS_WIN:
    import msvcrt
else:
    import tty, termios, select

G   = "\033[92m";  B  = "\033[94m";  Y  = "\033[93m"
R   = "\033[91m";  C  = "\033[96m";  W  = "\033[1;97m"
DIM = "\033[2m";   RST= "\033[0m";   M  = "\033[95m"
HIDE= "\033[?25l"; SHOW="\033[?25h"; UP = "\033[1A"; CLR="\033[2K"

ENV_FILE = os.path.join(os.path.dirname(__file__), ".env")

BANNER = f"""{C}
  ███╗   ██╗██╗███╗   ██╗ ██████╗  ██████╗██╗      █████╗ ██╗    ██╗
  ████╗  ██║██║████╗  ██║██╔═══██╗██╔════╝██║     ██╔══██╗██║    ██║
  ██╔██╗ ██║██║██╔██╗ ██║██║   ██║██║     ██║     ███████║██║ █╗ ██║
  ██║╚██╗██║██║██║╚██╗██║██║   ██║██║     ██║     ██╔══██║██║███╗██║
  ██║ ╚████║██║██║ ╚████║╚██████╔╝╚██████╗███████╗██║  ██║╚███╔███╔╝
  ╚═╝  ╚═══╝╚═╝╚═╝  ╚═══╝ ╚═════╝  ╚═════╝╚══════╝╚═╝  ╚═╝ ╚══╝╚══╝{RST}
{DIM}  Personal AI Assistant — Setup Wizard{RST}
"""

# ── helpers ──────────────────────────────────────────────────────────────────

def _getch():
    if _IS_WIN:
        ch = msvcrt.getwch()
        if ch in ('\x00', '\xe0'):  # special key prefix on Windows
            ch2 = msvcrt.getwch()
            # Map Windows arrow keys to ANSI escape sequences
            _map = {'H': '\x1b[A', 'P': '\x1b[B', 'K': '\x1b[D', 'M': '\x1b[C'}
            return _map.get(ch2, ch + ch2)
        return ch
    else:
        fd = sys.stdin.fileno()
        old = termios.tcgetattr(fd)
        try:
            tty.setraw(fd)
            ch = os.read(fd, 1).decode('latin-1')
            if ch == '\x1b':
                # wait up to 50ms for rest of escape sequence
                if select.select([fd], [], [], 0.05)[0]:
                    ch += os.read(fd, 2).decode('latin-1')
            return ch
        finally:
            termios.tcsetattr(fd, termios.TCSADRAIN, old)


def choose(prompt, options, default=0):
    """Arrow-key menu. options = list of (label, value)."""
    idx = default
    n   = len(options)
    print(f"\n  {W}{prompt}{RST}\n")
    for _ in options:
        print()
    sys.stdout.write(HIDE); sys.stdout.flush()

    def _render():
        for _ in range(n):
            sys.stdout.write(UP + "\r" + CLR)
        for i, (lbl, _) in enumerate(options):
            if i == idx:
                sys.stdout.write(f"\r  {G}❯ {W}{lbl}{RST}\n")
            else:
                sys.stdout.write(f"\r    {DIM}{lbl}{RST}\n")
        sys.stdout.flush()

    try:
        _render()
        while True:
            k = _getch()
            if   k in ('\x1b[A', '\x1b[D'): idx = (idx-1) % n
            elif k in ('\x1b[B', '\x1b[C'): idx = (idx+1) % n
            elif k in ('\r','\n',' '):       break
            elif k == '\x03':
                sys.stdout.write(SHOW); sys.exit(0)
            _render()
    finally:
        sys.stdout.write(SHOW); sys.stdout.flush()

    print(f"\n  {G}✓{RST}  {options[idx][0]}\n")
    return options[idx][1]


def ask(prompt, default=None, secret=False, optional=False):
    hint = f" {DIM}[{default}]{RST}" if default else (f" {DIM}(optional — press Enter to skip){RST}" if optional else "")
    try:
        if secret:
            val = getpass.getpass(f"  {C}❯{RST} {prompt}{hint}: ")
        else:
            val = input(f"  {C}❯{RST} {prompt}{hint}: ").strip()
    except (KeyboardInterrupt, EOFError):
        print(f"\n{Y}Cancelled.{RST}"); sys.exit(0)
    return (val.strip() or default) if val.strip() else (default if not optional else None)


def section(title):
    print(f"\n{M}  ── {W}{title}{RST}")


def ok(msg): print(f"  {G}✔{RST}  {msg}")
def info(msg): print(f"  {DIM}  {msg}{RST}")


def load_existing_env():
    data = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, _, v = line.partition("=")
                    data[k.strip()] = v.strip().strip('"')
    return data


def save_env(data):
    lines = ["# Ninoclaw config - generated by wizard\n"]
    for k, v in data.items():
        if v:
            lines.append(f'{k}="{v}"\n')
    with open(ENV_FILE, "w", encoding="utf-8") as f:
        f.writelines(lines)


# ── wizard ───────────────────────────────────────────────────────────────────

def run_wizard():
    e = load_existing_env()  # existing values
    print(BANNER)

    if e.get("TELEGRAM_BOT_TOKEN") and e["TELEGRAM_BOT_TOKEN"] != "YOUR_BOT_TOKEN_HERE":
        redo = choose("Existing config found. Re-run setup?",
                      [("Yes — reconfigure everything", True),
                       ("No  — keep current config",    False)])
        if not redo:
            return e

    cfg = {}

    # ── 1. Messaging Platforms ────────────────────────────────────────────────
    section("Step 1 — Messaging Platforms")

    _platforms = [
        ("Telegram   (recommended — most features)",   "telegram"),
        ("Discord    (@mention + DM support)",          "discord"),
    ]
    # Multi-select: toggle each platform
    selected = set()
    # Pre-select based on existing config
    if e.get("TELEGRAM_BOT_TOKEN") and e["TELEGRAM_BOT_TOKEN"] != "YOUR_BOT_TOKEN_HERE":
        selected.add("telegram")
    if e.get("DISCORD_BOT_TOKEN"):
        selected.add("discord")
    if not selected:
        selected.add("telegram")  # default

    # Multi-select menu
    print(f"\n  {W}Which platforms do you want to use?{RST}")
    info("Space = toggle  |  Enter = confirm  |  ↑↓ = move")
    n = len(_platforms)
    idx = 0

    def _render_platforms():
        for _ in range(n):
            sys.stdout.write(UP + "\r" + CLR)
        for i, (lbl, val) in enumerate(_platforms):
            check = f"{G}◉{RST}" if val in selected else f"{DIM}○{RST}"
            cursor = f"{G}❯ {W}" if i == idx else f"    {DIM}"
            sys.stdout.write(f"\r  {cursor}{check}  {lbl}{RST}\n")
        sys.stdout.flush()

    for _ in _platforms:
        print()
    sys.stdout.write(HIDE); sys.stdout.flush()
    try:
        _render_platforms()
        while True:
            k = _getch()
            if k in ('\x1b[A', '\x1b[D'):
                idx = (idx - 1) % n
            elif k in ('\x1b[B', '\x1b[C'):
                idx = (idx + 1) % n
            elif k == ' ':
                val = _platforms[idx][1]
                if val in selected:
                    selected.discard(val)
                else:
                    selected.add(val)
            elif k in ('\r', '\n'):
                break
            elif k == '\x03':
                sys.stdout.write(SHOW); sys.exit(0)
            _render_platforms()
    finally:
        sys.stdout.write(SHOW); sys.stdout.flush()

    if not selected:
        print(f"  {Y}⚠  No platform selected — defaulting to Telegram{RST}")
        selected.add("telegram")

    print(f"\n  {G}✓{RST}  Platforms: {', '.join(sorted(selected))}\n")

    # ── 1a. Telegram token ────────────────────────────────────────────────────
    if "telegram" in selected:
        section("Step 1a — Telegram Bot Token")
        info("Get yours from @BotFather on Telegram")
        token = ask("Bot Token", default=e.get("TELEGRAM_BOT_TOKEN"), secret=True)
        if not token or token == "YOUR_BOT_TOKEN_HERE":
            print(f"  {R}✗  Telegram token is required.{RST}"); sys.exit(1)
        cfg["TELEGRAM_BOT_TOKEN"] = token
        ok("Telegram token saved")
    else:
        cfg["TELEGRAM_BOT_TOKEN"] = e.get("TELEGRAM_BOT_TOKEN", "")

    # ── 1b. Discord token ─────────────────────────────────────────────────────
    if "discord" in selected:
        section("Step 1b — Discord Bot Token")
        info("Create bot: https://discord.com/developers/applications")
        info("Enable: Message Content Intent  |  Scope: bot + applications.commands")
        discord_token = ask("Discord Bot Token", default=e.get("DISCORD_BOT_TOKEN"), secret=True)
        if discord_token:
            cfg["DISCORD_BOT_TOKEN"] = discord_token
            ok("Discord token saved")
        else:
            print(f"  {Y}⚠  Skipped Discord (no token entered){RST}")
    else:
        cfg["DISCORD_BOT_TOKEN"] = e.get("DISCORD_BOT_TOKEN", "")

    # ── 2. AI Provider ────────────────────────────────────────────────────────
    section("Step 2 — AI Provider")
    provider = choose("Which AI provider?", [
        ("OpenRouter      (100+ models, free tier available)",  "openrouter"),
        ("Google Gemini   (free tier available)",               "gemini"),
        ("Groq            (free, very fast)",                   "groq"),
        ("OpenAI          (GPT-4o, GPT-4o-mini)",              "openai"),
        ("Mistral         (mistral-small free)",                "mistral"),
        ("xAI Grok        (grok-3-mini)",                       "xai"),
        ("ZhipuAI GLM     (glm-4-flash free)",                  "glm"),
        ("ZhipuAI GLM Coding Plan (GLM-4.7, paid)",            "glm_coding"),
        ("Anthropic Claude",                                    "anthropic"),
        ("Ollama          (local, offline)",                    "ollama"),
        ("Local Server    (llama.cpp, LM Studio, vLLM)",        "local"),
        ("Custom endpoint",                                     "custom"),
    ])

    if provider == "openrouter":
        info("Get key: https://openrouter.ai/keys  (free signup)")
        info("Free models end with :free  e.g.  google/gemini-2.0-flash-exp:free")
        cfg["OPENAI_API_URL"] = "https://openrouter.ai/api/v1"
        cfg["OPENAI_API_KEY"] = ask("OpenRouter API Key", default=e.get("OPENAI_API_KEY"), secret=True) or ""
        cfg["OPENAI_MODEL"]   = ask("Model", default=e.get("OPENAI_MODEL", "google/gemini-2.0-flash-exp:free")) or ""
        cfg["OPENROUTER_API_KEY"] = cfg["OPENAI_API_KEY"]

    elif provider == "gemini":
        info("Get key: https://aistudio.google.com/app/apikey")
        cfg["OPENAI_API_URL"] = "https://generativelanguage.googleapis.com/v1beta/openai"
        cfg["OPENAI_API_KEY"] = ask("Gemini API Key", default=e.get("OPENAI_API_KEY"), secret=True) or ""
        cfg["OPENAI_MODEL"]   = ask("Model", default=e.get("OPENAI_MODEL", "gemini-3-flash-preview")) or ""

    elif provider == "groq":
        info("Get key: https://console.groq.com")
        cfg["OPENAI_API_URL"] = "https://api.groq.com/openai/v1"
        cfg["OPENAI_API_KEY"] = ask("Groq API Key", default=e.get("OPENAI_API_KEY"), secret=True) or ""
        cfg["OPENAI_MODEL"]   = ask("Model", default=e.get("OPENAI_MODEL", "llama-3.3-70b-versatile")) or ""

    elif provider == "openai":
        cfg["OPENAI_API_URL"] = "https://api.openai.com/v1"
        cfg["OPENAI_API_KEY"] = ask("OpenAI API Key", default=e.get("OPENAI_API_KEY"), secret=True) or ""
        cfg["OPENAI_MODEL"]   = ask("Model", default=e.get("OPENAI_MODEL", "gpt-4o-mini")) or ""

    elif provider == "mistral":
        cfg["OPENAI_API_URL"] = "https://api.mistral.ai/v1"
        cfg["OPENAI_API_KEY"] = ask("Mistral API Key", default=e.get("OPENAI_API_KEY"), secret=True) or ""
        cfg["OPENAI_MODEL"]   = ask("Model", default=e.get("OPENAI_MODEL", "mistral-small-latest")) or ""

    elif provider == "xai":
        cfg["OPENAI_API_URL"] = "https://api.x.ai/v1"
        cfg["OPENAI_API_KEY"] = ask("xAI API Key", default=e.get("OPENAI_API_KEY"), secret=True) or ""
        cfg["OPENAI_MODEL"]   = ask("Model", default=e.get("OPENAI_MODEL", "grok-3-mini")) or ""

    elif provider == "glm":
        cfg["OPENAI_API_URL"] = "https://open.bigmodel.cn/api/paas/v4"
        cfg["OPENAI_API_KEY"] = ask("ZhipuAI API Key", default=e.get("OPENAI_API_KEY"), secret=True) or ""
        cfg["OPENAI_MODEL"]   = ask("Model", default=e.get("OPENAI_MODEL", "glm-4-flash")) or ""

    elif provider == "glm_coding":
        info("Get key: https://z.ai  (GLM Coding Plan from $3/month)")
        cfg["OPENAI_API_URL"] = "https://api.z.ai/api/coding/paas/v4"
        cfg["OPENAI_API_KEY"] = ask("Z.AI API Key", default=e.get("OPENAI_API_KEY"), secret=True) or ""
        cfg["OPENAI_MODEL"]   = ask("Model", default=e.get("OPENAI_MODEL", "GLM-4.7")) or ""
        cfg["GLM_CODING_API_KEY"]   = cfg["OPENAI_API_KEY"]
        cfg["GLM_CODING_MODEL"]     = cfg["OPENAI_MODEL"]

    elif provider == "anthropic":
        cfg["OPENAI_API_URL"] = "https://api.anthropic.com/v1"
        cfg["OPENAI_API_KEY"] = ask("Anthropic API Key", default=e.get("OPENAI_API_KEY"), secret=True) or ""
        cfg["OPENAI_MODEL"]   = ask("Model", default=e.get("OPENAI_MODEL", "claude-3-5-sonnet-20241022")) or ""

    elif provider == "ollama":
        info("Make sure Ollama is running: ollama serve")
        cfg["OPENAI_API_URL"] = ask("Ollama URL", default=e.get("OPENAI_API_URL", "http://localhost:11434/v1")) or ""
        cfg["OPENAI_API_KEY"] = "ollama"
        cfg["OPENAI_MODEL"]   = ask("Model", default=e.get("OPENAI_MODEL", "llama3.2")) or ""

    elif provider == "local":
        info("Make sure your local server is running (e.g. llama-server -hf ... --port 8000)")
        info("Warning: Do not use port 8080 if your Ninoclaw web dashboard uses it.")
        cfg["OPENAI_API_URL"] = ask("Local API Base URL", default=e.get("OPENAI_API_URL", "http://127.0.0.1:8000/v1")) or ""
        cfg["OPENAI_API_KEY"] = ask("API Key (usually 'local')", default="local") or "local"
        cfg["OPENAI_MODEL"]   = ask("Model name (usually ignored by local servers)", default="local-model") or "local-model"

    else:  # custom
        cfg["OPENAI_API_URL"] = ask("API Base URL", default=e.get("OPENAI_API_URL")) or ""
        cfg["OPENAI_API_KEY"] = ask("API Key", default=e.get("OPENAI_API_KEY"), secret=True) or ""
        cfg["OPENAI_MODEL"]   = ask("Model name", default=e.get("OPENAI_MODEL")) or ""

    ok(f"Provider: {provider}  |  Model: {cfg['OPENAI_MODEL']}")

    # ── 3. Fallback providers ─────────────────────────────────────────────────
    section("Step 3 — Fallback Providers  (optional)")
    info("Bot tries these in order if primary fails. Press Enter to skip any.")
    _fallbacks = [
        ("OpenRouter API Key",      "OPENROUTER_API_KEY", "https://openrouter.ai — free models available"),
        ("Groq API Key",           "GROQ_API_KEY",        "https://console.groq.com — free"),
        ("Mistral API Key",        "MISTRAL_API_KEY",      "https://console.mistral.ai"),
        ("xAI Grok API Key",       "XAI_API_KEY",          "https://console.x.ai"),
        ("GLM API Key",            "GLM_API_KEY",           "https://open.bigmodel.cn"),
        ("GLM Coding API Key",     "GLM_CODING_API_KEY",    "https://z.ai — GLM-4.7 coding model"),
        ("Ollama model name",      "OLLAMA_MODEL",          "e.g. llama3.2 — local"),
    ]
    for label, key, hint in _fallbacks:
        if cfg.get(key): continue  # already set as primary
        info(hint)
        val = ask(label, default=e.get(key), optional=True,
                  secret=(key != "OLLAMA_MODEL"))
        if val:
            cfg[key] = val
            ok(f"{label.split()[0]} added")

    # ── 4. Web Search ─────────────────────────────────────────────────────────
    section("Step 4 — Web Search  (optional)")
    info("Free at https://serper.dev — 2500 searches/month")
    serper = ask("Serper API Key", default=e.get("SERPER_API_KEY"), optional=True, secret=True)
    if serper:
        cfg["SERPER_API_KEY"] = serper
        ok("Web search enabled")
    else:
        ok("Skipped")

    # ── 5. Owner ID ───────────────────────────────────────────────────────────
    section("Step 5 — Your Telegram User ID  (recommended)")
    info("Message @userinfobot on Telegram to get your ID")
    owner = ask("Your Telegram user ID", default=e.get("OWNER_ID"), optional=True)
    if owner:
        cfg["OWNER_ID"] = owner
        ok(f"Owner locked to {owner}")
    else:
        ok("Skipped")

    # ── 6. Personalization ────────────────────────────────────────────────────
    section("Step 6 — Personalization")
    cfg["AGENT_NAME"]  = ask("Bot name",    default=e.get("AGENT_NAME",  "Ninoclaw")) or "Ninoclaw"
    cfg["USER_NAME"]   = ask("Your name",   default=e.get("USER_NAME",   "friend"))   or "friend"
    cfg["BOT_PURPOSE"] = ask("Bot purpose", default=e.get("BOT_PURPOSE", "be your personal AI assistant")) or "be your personal AI assistant"
    cfg["TIMEZONE"]    = ask("Timezone",    default=e.get("TIMEZONE",    "UTC"))       or "UTC"
    ok(f"{cfg['AGENT_NAME']} ready for {cfg['USER_NAME']} ({cfg['TIMEZONE']})")

    # ── 7. Email (Resend) ─────────────────────────────────────────────────────
    section("Step 7 — Email via Resend  (optional)")
    info("Free at https://resend.com — 100 emails/day")
    resend_key = ask("Resend API Key", default=e.get("RESEND_API_KEY"), optional=True, secret=True)
    if resend_key:
        cfg["RESEND_API_KEY"] = resend_key
        cfg["RESEND_FROM"]    = ask("From address", default=e.get("RESEND_FROM", "onboarding@resend.dev")) or ""
        cfg["OWNER_EMAIL"]    = ask("Your email",   default=e.get("OWNER_EMAIL")) or ""
        ok("Resend configured — load skill in Telegram to activate")
    else:
        ok("Skipped")

    # ── 8. Image Generation ───────────────────────────────────────────────────
    section("Step 8 — Image Generation  (optional)")
    info("Free option: HuggingFace (FLUX.1-schnell) — get token at https://huggingface.co/settings/tokens")
    info("Paid option: fal.ai (FLUX.1 Schnell) — get key at https://fal.ai")
    info("Fallback: Google Gemini Nano Banana — get key at https://aistudio.google.com/apikey")
    hf_token = ask("HuggingFace Token (free, recommended)", default=e.get("HF_TOKEN"), optional=True, secret=True)
    if hf_token:
        cfg["HF_TOKEN"] = hf_token
        ok("HuggingFace FLUX.1-schnell enabled — say 'generate an image of...' in Telegram")
    else:
        ok("Skipped HuggingFace")
    fal_key = ask("fal.ai API Key (optional)", default=e.get("FAL_KEY"), optional=True, secret=True)
    if fal_key:
        cfg["FAL_KEY"] = fal_key
        ok("fal.ai FLUX enabled")
    else:
        ok("Skipped fal.ai")
    # Gemini fallback
    is_gemini = "generativelanguage.googleapis.com" in cfg.get("OPENAI_API_URL", e.get("OPENAI_API_URL", ""))
    if is_gemini:
        info("Gemini fallback: reusing your existing Gemini API key ✅")
        cfg["GEMINI_API_KEY"] = cfg.get("OPENAI_API_KEY") or e.get("OPENAI_API_KEY", "")
    else:
        gemini_key = ask("Gemini API Key (fallback, optional)", default=e.get("GEMINI_API_KEY"), optional=True, secret=True)
        if gemini_key:
            cfg["GEMINI_API_KEY"] = gemini_key

    # ── 9. Dashboard ──────────────────────────────────────────────────────────
    section("Step 9 — Web Dashboard")
    cfg["DASHBOARD_PASSWORD"] = ask("Dashboard password", default=e.get("DASHBOARD_PASSWORD", "admin")) or "admin"
    cfg["DASHBOARD_PORT"]     = ask("Dashboard port",     default=e.get("DASHBOARD_PORT", "8080"))       or "8080"
    ok(f"Dashboard at http://localhost:{cfg['DASHBOARD_PORT']}")

    # ── Save ──────────────────────────────────────────────────────────────────
    save_env(cfg)
    print(f"\n{G}  ✔  Config saved to .env{RST}")
    print(f"{C}  🦀 Run: ninoclaw start{RST}\n")
    return cfg


def needs_setup():
    e = load_existing_env()
    token = e.get("TELEGRAM_BOT_TOKEN", "")
    discord = e.get("DISCORD_BOT_TOKEN", "")
    has_telegram = token and token != "YOUR_BOT_TOKEN_HERE"
    has_discord  = bool(discord)
    return not has_telegram and not has_discord


if __name__ == "__main__":
    run_wizard()
