"""
Ninoclaw Setup Wizard — interactive first-run CLI
"""
import os
import sys

# ANSI colors
G  = "\033[92m"   # green
B  = "\033[94m"   # blue
Y  = "\033[93m"   # yellow
R  = "\033[91m"   # red
C  = "\033[96m"   # cyan
W  = "\033[97m"   # white bold
DIM = "\033[2m"
RST = "\033[0m"

ENV_FILE = os.path.join(os.path.dirname(__file__), ".env")

BANNER = f"""
{C}╔══════════════════════════════════════════╗
║         🦀  NINOCLAW  SETUP  🦀          ║
║     Personal AI Assistant Gateway        ║
╚══════════════════════════════════════════╝{RST}
"""

def ask(prompt, default=None, secret=False, optional=False):
    """Prompt user for input with optional default"""
    hint = ""
    if default:
        hint = f" {DIM}[{default}]{RST}"
    elif optional:
        hint = f" {DIM}[skip]{RST}"

    try:
        if secret:
            import getpass
            val = getpass.getpass(f"  {B}>{RST} {prompt}{hint}: ")
        else:
            val = input(f"  {B}>{RST} {prompt}{hint}: ").strip()
    except (KeyboardInterrupt, EOFError):
        print(f"\n{Y}Setup cancelled.{RST}")
        sys.exit(0)

    if not val and default:
        return default
    return val or None


def choose(prompt, options, default_idx=0):
    """Show a numbered menu and return chosen value"""
    print(f"\n  {W}{prompt}{RST}")
    for i, (label, _) in enumerate(options):
        marker = f"{G}▶{RST}" if i == default_idx else " "
        print(f"  {marker} {i+1}. {label}")
    while True:
        try:
            raw = input(f"  {B}>{RST} Choice [{default_idx+1}]: ").strip()
        except (KeyboardInterrupt, EOFError):
            print(f"\n{Y}Setup cancelled.{RST}")
            sys.exit(0)
        if not raw:
            return options[default_idx][1]
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return options[int(raw)-1][1]
        print(f"  {R}Invalid choice.{RST}")


def section(title):
    print(f"\n{Y}── {title} {'─' * (40 - len(title))}{RST}")


def ok(msg):
    print(f"  {G}✓{RST} {msg}")


def load_existing_env():
    """Load existing .env into a dict"""
    data = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, _, v = line.partition("=")
                    data[k.strip()] = v.strip().strip('"')
    return data


def save_env(data):
    """Write dict to .env file"""
    lines = ["# Ninoclaw configuration — generated by setup wizard\n"]
    for k, v in data.items():
        lines.append(f'{k}="{v}"\n')
    with open(ENV_FILE, "w") as f:
        f.writelines(lines)


def run_wizard():
    existing = load_existing_env()
    print(BANNER)

    if existing:
        print(f"  {Y}Existing config found.{RST} Re-running wizard will overwrite it.\n")
        try:
            confirm = input(f"  {B}>{RST} Continue? (y/N): ").strip().lower()
        except (KeyboardInterrupt, EOFError):
            sys.exit(0)
        if confirm != "y":
            return existing

    config = {}

    # ── Telegram ────────────────────────────────────────────────────────────
    section("Telegram Bot Token")
    print(f"  {DIM}Get yours from @BotFather on Telegram{RST}")
    token = ask("Bot Token", default=existing.get("TELEGRAM_BOT_TOKEN"), secret=True)
    if not token or token == "YOUR_BOT_TOKEN_HERE":
        print(f"  {R}✗ Telegram token is required.{RST}")
        sys.exit(1)
    config["TELEGRAM_BOT_TOKEN"] = token
    ok("Telegram token saved")

    # ── AI Provider ─────────────────────────────────────────────────────────
    section("AI Model (Primary)")
    provider = choose("Which AI provider?", [
        ("Google Gemini  (free tier available)",        "gemini"),
        ("OpenAI  (GPT-4o, GPT-4o-mini, etc.)",        "openai"),
        ("Anthropic Claude (claude-3-5-sonnet, etc.)", "anthropic"),
        ("Custom OpenAI-compatible endpoint",           "custom"),
    ])

    if provider == "gemini":
        print(f"  {DIM}Get API key: https://aistudio.google.com/app/apikey{RST}")
        config["OPENAI_API_URL"] = "https://generativelanguage.googleapis.com/v1beta/openai"
        config["OPENAI_API_KEY"] = ask("Gemini API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = choose("Model", [
            ("gemini-3-flash-preview  (latest, smartest)", "gemini-3-flash-preview"),
            ("gemini-2.0-flash  (fast, stable)",           "gemini-2.0-flash"),
            ("gemini-1.5-flash  (stable)",                 "gemini-1.5-flash"),
            ("gemini-1.5-pro   (smarter, slower)",         "gemini-1.5-pro"),
        ]) or "gemini-3-flash-preview"

    elif provider == "openai":
        print(f"  {DIM}Get API key: https://platform.openai.com/api-keys{RST}")
        config["OPENAI_API_URL"] = "https://api.openai.com/v1"
        config["OPENAI_API_KEY"] = ask("OpenAI API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = choose("Model", [
            ("gpt-4o-mini  (cheap, fast)",   "gpt-4o-mini"),
            ("gpt-4o       (best quality)",  "gpt-4o"),
        ]) or "gpt-4o-mini"

    elif provider == "anthropic":
        print(f"  {DIM}Get API key: https://console.anthropic.com/{RST}")
        config["OPENAI_API_URL"] = "https://api.anthropic.com/v1"
        config["OPENAI_API_KEY"] = ask("Anthropic API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = ask("Model", default="claude-3-5-sonnet-20241022") or "claude-3-5-sonnet-20241022"

    else:  # custom
        config["OPENAI_API_URL"] = ask("API base URL", default=existing.get("OPENAI_API_URL")) or ""
        config["OPENAI_API_KEY"] = ask("API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = ask("Model name", default=existing.get("OPENAI_MODEL")) or ""

    ok(f"Primary model: {config['OPENAI_MODEL']}")

    # ── Fallback model ───────────────────────────────────────────────────────
    section("Fallback Model (optional)")
    print(f"  {DIM}Used automatically if the primary model fails or hits rate limits{RST}")
    want_fallback = input(f"  {B}>{RST} Add a fallback model? (y/N): ").strip().lower()
    if want_fallback == "y":
        config["FALLBACK_MODEL"]   = ask("Fallback model name", default=existing.get("FALLBACK_MODEL")) or ""
        fb_key = ask("Fallback API key (leave blank to reuse primary key)", optional=True, secret=True)
        if fb_key:
            config["FALLBACK_API_KEY"] = fb_key
        fb_url = ask("Fallback API URL (leave blank to reuse primary URL)", optional=True)
        if fb_url:
            config["FALLBACK_API_URL"] = fb_url
        if config["FALLBACK_MODEL"]:
            ok(f"Fallback model: {config['FALLBACK_MODEL']}")
    else:
        ok("Skipped")

    # ── Web Search ───────────────────────────────────────────────────────────
    section("Web Search — Serper API (optional)")
    print(f"  {DIM}Enables real-time Google search. Free tier: https://serper.dev{RST}")
    serper = ask("Serper API Key", default=existing.get("SERPER_API_KEY"), optional=True, secret=True)
    if serper:
        config["SERPER_API_KEY"] = serper
        ok("Web search enabled")
    else:
        ok("Skipped — web search will be disabled")

    # ── Owner ID ─────────────────────────────────────────────────────────────
    section("Bot Owner Telegram ID (recommended)")
    print(f"  {DIM}Only you can run /update and admin commands. Message @userinfobot to get your ID.{RST}")
    owner = ask("Your Telegram user ID", default=existing.get("OWNER_ID"), optional=True)
    if owner:
        config["OWNER_ID"] = owner
        ok(f"Owner ID: {owner}")
    else:
        ok("Skipped — anyone can run admin commands!")

    # ── Save ─────────────────────────────────────────────────────────────────
    save_env(config)
    print(f"\n{G}✅ Config saved to .env — starting Ninoclaw...{RST}\n")
    return config


def needs_setup():
    """Returns True if .env is missing or has no valid token"""
    existing = load_existing_env()
    token = existing.get("TELEGRAM_BOT_TOKEN", "")
    return not token or token == "YOUR_BOT_TOKEN_HERE"
