"""
Ninoclaw Setup Wizard — interactive first-run CLI with arrow-key navigation
"""
import os
import sys
import tty
import termios

# ANSI codes
G    = "\033[92m"
B    = "\033[94m"
Y    = "\033[93m"
R    = "\033[91m"
C    = "\033[96m"
M    = "\033[95m"
W    = "\033[1;97m"
DIM  = "\033[2m"
RST  = "\033[0m"
HIDE = "\033[?25l"   # hide cursor
SHOW = "\033[?25h"   # show cursor
UP   = "\033[1A"
CLR  = "\033[2K"

ENV_FILE = os.path.join(os.path.dirname(__file__), ".env")

BANNER = f"""
{C}
  ███╗   ██╗██╗███╗   ██╗ ██████╗  ██████╗██╗      █████╗ ██╗    ██╗
  ████╗  ██║██║████╗  ██║██╔═══██╗██╔════╝██║     ██╔══██╗██║    ██║
  ██╔██╗ ██║██║██╔██╗ ██║██║   ██║██║     ██║     ███████║██║ █╗ ██║
  ██║╚██╗██║██║██║╚██╗██║██║   ██║██║     ██║     ██╔══██║██║███╗██║
  ██║ ╚████║██║██║ ╚████║╚██████╔╝╚██████╗███████╗██║  ██║╚███╔███╔╝
  ╚═╝  ╚═══╝╚═╝╚═╝  ╚═══╝ ╚═════╝  ╚═════╝╚══════╝╚═╝  ╚═╝ ╚══╝╚══╝
{RST}
{DIM}  Personal AI Assistant — Setup Wizard{RST}
"""


def _getch():
    """Read a single keypress (including arrow keys)"""
    fd = sys.stdin.fileno()
    old = termios.tcgetattr(fd)
    try:
        tty.setraw(fd)
        ch = sys.stdin.read(1)
        if ch == '\x1b':
            ch2 = sys.stdin.read(1)
            ch3 = sys.stdin.read(1)
            return ch + ch2 + ch3
        return ch
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old)


def choose(prompt, options, default_idx=0):
    """Arrow-key navigable menu. Returns chosen value."""
    idx = default_idx
    n   = len(options)

    print(f"\n  {W}{prompt}{RST}")
    # Print all options first
    for i, (label, _) in enumerate(options):
        print()

    print(HIDE, end="", flush=True)

    def render():
        # Move cursor up to start of options
        for _ in range(n):
            sys.stdout.write(UP + CLR)
        for i, (label, _) in enumerate(options):
            if i == idx:
                sys.stdout.write(f"  {G}❯{RST} {W}{label}{RST}\n")
            else:
                sys.stdout.write(f"  {DIM}  {label}{RST}\n")
        sys.stdout.flush()

    render()

    try:
        while True:
            key = _getch()
            if key in ('\x1b[A', '\x1b[D'):   # up / left
                idx = (idx - 1) % n
            elif key in ('\x1b[B', '\x1b[C'): # down / right
                idx = (idx + 1) % n
            elif key in ('\r', '\n', ' '):     # enter / space
                break
            elif key == '\x03':                # ctrl-c
                print(SHOW)
                print(f"\n{Y}Setup cancelled.{RST}")
                sys.exit(0)
            render()
    finally:
        print(SHOW, end="", flush=True)

    label, value = options[idx]
    print(f"\n  {G}✓{RST} {label}\n")
    return value


def ask(prompt, default=None, secret=False, optional=False):
    """Prompt for text input"""
    hint = f" {DIM}[{default}]{RST}" if default else (f" {DIM}(optional){RST}" if optional else "")
    try:
        if secret:
            import getpass
            val = getpass.getpass(f"  {B}❯{RST} {W}{prompt}{RST}{hint} ")
        else:
            val = input(f"  {B}❯{RST} {W}{prompt}{RST}{hint} ").strip()
    except (KeyboardInterrupt, EOFError):
        print(f"\n{Y}Setup cancelled.{RST}")
        sys.exit(0)
    return val.strip() if val else (default or None)


def confirm(prompt):
    """Yes/No using arrow keys"""
    return choose(prompt, [("Yes", True), ("No", False)], default_idx=0)


def section(title):
    w = 48
    pad = w - len(title) - 4
    print(f"\n{M}  ┌─ {title} {'─' * pad}┐{RST}")


def ok(msg):
    print(f"  {G}✔{RST}  {msg}")


def load_existing_env():
    data = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, _, v = line.partition("=")
                    data[k.strip()] = v.strip().strip('"')
    return data


def save_env(data):
    lines = ["# Ninoclaw configuration — generated by setup wizard\n"]
    for k, v in data.items():
        lines.append(f'{k}="{v}"\n')
    with open(ENV_FILE, "w") as f:
        f.writelines(lines)


def run_wizard():
    existing = load_existing_env()
    print(BANNER)

    if existing:
        print(f"  {Y}Existing config found.{RST}")
        if not confirm("Re-run setup and overwrite it?"):
            return existing

    config = {}

    # ── Telegram ─────────────────────────────────────────────────────────────
    section("Telegram Bot Token")
    print(f"  {DIM}  Get yours from @BotFather on Telegram{RST}\n")
    token = ask("Bot Token", default=existing.get("TELEGRAM_BOT_TOKEN"), secret=True)
    if not token or token == "YOUR_BOT_TOKEN_HERE":
        print(f"  {R}✗ Telegram token is required.{RST}")
        sys.exit(1)
    config["TELEGRAM_BOT_TOKEN"] = token
    ok("Telegram token saved")

    # ── AI Provider ───────────────────────────────────────────────────────────
    section("AI Provider")
    provider = choose("Which AI provider?", [
        ("Google Gemini       (free tier available)",  "gemini"),
        ("Groq                (free, very fast — llama/mixtral)", "groq"),
        ("OpenAI              (GPT-4o, GPT-4o-mini)", "openai"),
        ("Mistral             (mistral-small free)",  "mistral"),
        ("xAI Grok            (grok-3-mini)",         "xai"),
        ("ZhipuAI GLM         (glm-4-flash free)",    "glm"),
        ("MiniMax             (MiniMax-Text-01)",      "minimax"),
        ("Together AI         (100+ open models)",    "together"),
        ("OpenRouter          (all providers in one)", "openrouter"),
        ("Anthropic Claude    (claude-3-5-sonnet)",   "anthropic"),
        ("Custom OpenAI-compatible endpoint",         "custom"),
    ])

    if provider == "gemini":
        print(f"  {DIM}  Get key: https://aistudio.google.com/app/apikey{RST}\n")
        config["OPENAI_API_URL"] = "https://generativelanguage.googleapis.com/v1beta/openai"
        config["OPENAI_API_KEY"] = ask("Gemini API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = choose("Model", [
            ("gemini-2.0-flash         (fast, stable)",     "gemini-2.0-flash"),
            ("gemini-1.5-flash         (stable)",           "gemini-1.5-flash"),
            ("gemini-1.5-pro           (smarter, slower)",  "gemini-1.5-pro"),
        ])

    elif provider == "groq":
        print(f"  {DIM}  Get key: https://console.groq.com{RST}\n")
        config["OPENAI_API_URL"] = "https://api.groq.com/openai/v1"
        config["OPENAI_API_KEY"] = ask("Groq API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = choose("Model", [
            ("llama-3.3-70b-versatile  (best quality)", "llama-3.3-70b-versatile"),
            ("llama-3.1-8b-instant     (fastest)",      "llama-3.1-8b-instant"),
            ("mixtral-8x7b-32768       (good balance)", "mixtral-8x7b-32768"),
        ])

    elif provider == "openai":
        print(f"  {DIM}  Get key: https://platform.openai.com/api-keys{RST}\n")
        config["OPENAI_API_URL"] = "https://api.openai.com/v1"
        config["OPENAI_API_KEY"] = ask("OpenAI API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = choose("Model", [
            ("gpt-4o-mini   (cheap, fast)",  "gpt-4o-mini"),
            ("gpt-4o        (best quality)", "gpt-4o"),
        ])

    elif provider == "mistral":
        print(f"  {DIM}  Get key: https://console.mistral.ai{RST}\n")
        config["OPENAI_API_URL"] = "https://api.mistral.ai/v1"
        config["OPENAI_API_KEY"] = ask("Mistral API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = choose("Model", [
            ("mistral-small-latest  (free tier)", "mistral-small-latest"),
            ("mistral-large-latest  (best)",      "mistral-large-latest"),
        ])

    elif provider == "xai":
        print(f"  {DIM}  Get key: https://console.x.ai{RST}\n")
        config["OPENAI_API_URL"] = "https://api.x.ai/v1"
        config["OPENAI_API_KEY"] = ask("xAI API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = ask("Model", default="grok-3-mini") or "grok-3-mini"

    elif provider == "glm":
        print(f"  {DIM}  Get key: https://open.bigmodel.cn{RST}\n")
        config["OPENAI_API_URL"] = "https://open.bigmodel.cn/api/paas/v4"
        config["OPENAI_API_KEY"] = ask("GLM API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = choose("Model", [
            ("glm-4-flash  (free tier)", "glm-4-flash"),
            ("glm-4-plus   (best)",      "glm-4-plus"),
        ])

    elif provider == "minimax":
        print(f"  {DIM}  Get key: https://api.minimax.chat{RST}\n")
        config["OPENAI_API_URL"] = "https://api.minimax.chat/v1"
        config["OPENAI_API_KEY"] = ask("MiniMax API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = ask("Model", default="MiniMax-Text-01") or "MiniMax-Text-01"

    elif provider == "together":
        print(f"  {DIM}  Get key: https://api.together.xyz{RST}\n")
        config["OPENAI_API_URL"] = "https://api.together.xyz/v1"
        config["OPENAI_API_KEY"] = ask("Together API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = ask("Model", default="meta-llama/Llama-3-70b-chat-hf") or ""

    elif provider == "openrouter":
        print(f"  {DIM}  Get key: https://openrouter.ai/keys{RST}\n")
        config["OPENAI_API_URL"] = "https://openrouter.ai/api/v1"
        config["OPENAI_API_KEY"] = ask("OpenRouter API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = ask("Model", default="openai/gpt-4o-mini") or ""

    elif provider == "anthropic":
        print(f"  {DIM}  Get key: https://console.anthropic.com/{RST}\n")
        config["OPENAI_API_URL"] = "https://api.anthropic.com/v1"
        config["OPENAI_API_KEY"] = ask("Anthropic API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = ask("Model", default="claude-3-5-sonnet-20241022") or ""

    else:
        config["OPENAI_API_URL"] = ask("API base URL", default=existing.get("OPENAI_API_URL")) or ""
        config["OPENAI_API_KEY"] = ask("API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = ask("Model name", default=existing.get("OPENAI_MODEL")) or ""

    ok(f"Primary model: {config['OPENAI_MODEL']}")

    # ── Extra providers (fallback chain) ──────────────────────────────────────
    section("Extra Providers  (fallback chain — optional)")
    print(f"  {DIM}  Bot tries these in order if primary fails/rate-limits. Skip any with Enter.{RST}\n")
    _extra = [
        ("Groq",       "GROQ_API_KEY",       "https://console.groq.com"),
        ("Mistral",    "MISTRAL_API_KEY",     "https://console.mistral.ai"),
        ("xAI Grok",   "XAI_API_KEY",         "https://console.x.ai"),
        ("ZhipuAI GLM","GLM_API_KEY",         "https://open.bigmodel.cn"),
        ("MiniMax",    "MINIMAX_API_KEY",     "https://api.minimax.chat"),
        ("Together AI","TOGETHER_API_KEY",    "https://api.together.xyz"),
        ("OpenRouter", "OPENROUTER_API_KEY",  "https://openrouter.ai"),
        ("Ollama (local)", "OLLAMA_MODEL",    "ollama serve"),
    ]
    for name, key_var, hint in _extra:
        val = ask(f"{name} key/model ({hint})", default=existing.get(key_var), optional=True, secret=(key_var != "OLLAMA_MODEL"))
        if val:
            config[key_var] = val
            ok(f"{name} added to fallback chain")
        else:
            ok(f"{name} skipped")

    # ── Web Search ────────────────────────────────────────────────────────────
    section("Web Search  (Serper API)")
    print(f"  {DIM}  Free tier at https://serper.dev — enables real-time Google search{RST}\n")
    serper = ask("Serper API Key", default=existing.get("SERPER_API_KEY"), optional=True, secret=True)
    if serper:
        config["SERPER_API_KEY"] = serper
        ok("Web search enabled")
    else:
        ok("Skipped — web search disabled")

    # ── Owner ID ──────────────────────────────────────────────────────────────
    section("Bot Owner ID")
    print(f"  {DIM}  Message @userinfobot on Telegram to get your ID{RST}\n")
    owner = ask("Your Telegram user ID", default=existing.get("OWNER_ID"), optional=True)
    if owner:
        config["OWNER_ID"] = owner
        ok(f"Owner locked to ID {owner}")
    else:
        ok("Skipped — admin commands open to all users!")

    # ── Done ──────────────────────────────────────────────────────────────────
    save_env(config)
    print(f"\n{G}  ✔  Config saved to .env{RST}\n")
    print(f"{C}  🦀 Starting Ninoclaw...{RST}\n")
    return config


def needs_setup():
    existing = load_existing_env()
    token = existing.get("TELEGRAM_BOT_TOKEN", "")
    return not token or token == "YOUR_BOT_TOKEN_HERE"


# ANSI colors
G  = "\033[92m"   # green
B  = "\033[94m"   # blue
Y  = "\033[93m"   # yellow
R  = "\033[91m"   # red
C  = "\033[96m"   # cyan
W  = "\033[97m"   # white bold
DIM = "\033[2m"
RST = "\033[0m"

ENV_FILE = os.path.join(os.path.dirname(__file__), ".env")

BANNER = f"""
{C}╔══════════════════════════════════════════╗
║         🦀  NINOCLAW  SETUP  🦀          ║
║     Personal AI Assistant Gateway        ║
╚══════════════════════════════════════════╝{RST}
"""

def ask(prompt, default=None, secret=False, optional=False):
    """Prompt user for input with optional default"""
    hint = ""
    if default:
        hint = f" {DIM}[{default}]{RST}"
    elif optional:
        hint = f" {DIM}[skip]{RST}"

    try:
        if secret:
            import getpass
            val = getpass.getpass(f"  {B}>{RST} {prompt}{hint}: ")
        else:
            val = input(f"  {B}>{RST} {prompt}{hint}: ").strip()
    except (KeyboardInterrupt, EOFError):
        print(f"\n{Y}Setup cancelled.{RST}")
        sys.exit(0)

    if not val and default:
        return default
    return val or None


def choose(prompt, options, default_idx=0):
    """Show a numbered menu and return chosen value"""
    print(f"\n  {W}{prompt}{RST}")
    for i, (label, _) in enumerate(options):
        marker = f"{G}▶{RST}" if i == default_idx else " "
        print(f"  {marker} {i+1}. {label}")
    while True:
        try:
            raw = input(f"  {B}>{RST} Choice [{default_idx+1}]: ").strip()
        except (KeyboardInterrupt, EOFError):
            print(f"\n{Y}Setup cancelled.{RST}")
            sys.exit(0)
        if not raw:
            return options[default_idx][1]
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return options[int(raw)-1][1]
        print(f"  {R}Invalid choice.{RST}")


def section(title):
    print(f"\n{Y}── {title} {'─' * (40 - len(title))}{RST}")


def ok(msg):
    print(f"  {G}✓{RST} {msg}")


def load_existing_env():
    """Load existing .env into a dict"""
    data = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, _, v = line.partition("=")
                    data[k.strip()] = v.strip().strip('"')
    return data


def save_env(data):
    """Write dict to .env file"""
    lines = ["# Ninoclaw configuration — generated by setup wizard\n"]
    for k, v in data.items():
        lines.append(f'{k}="{v}"\n')
    with open(ENV_FILE, "w") as f:
        f.writelines(lines)


def run_wizard():
    existing = load_existing_env()
    print(BANNER)

    if existing:
        print(f"  {Y}Existing config found.{RST} Re-running wizard will overwrite it.\n")
        try:
            confirm = input(f"  {B}>{RST} Continue? (y/N): ").strip().lower()
        except (KeyboardInterrupt, EOFError):
            sys.exit(0)
        if confirm != "y":
            return existing

    config = {}

    # ── Telegram ────────────────────────────────────────────────────────────
    section("Telegram Bot Token")
    print(f"  {DIM}Get yours from @BotFather on Telegram{RST}")
    token = ask("Bot Token", default=existing.get("TELEGRAM_BOT_TOKEN"), secret=True)
    if not token or token == "YOUR_BOT_TOKEN_HERE":
        print(f"  {R}✗ Telegram token is required.{RST}")
        sys.exit(1)
    config["TELEGRAM_BOT_TOKEN"] = token
    ok("Telegram token saved")

    # ── AI Provider ─────────────────────────────────────────────────────────
    section("AI Model (Primary)")
    provider = choose("Which AI provider?", [
        ("Google Gemini  (free tier available)",        "gemini"),
        ("Groq           (free, very fast)",            "groq"),
        ("OpenAI         (GPT-4o, GPT-4o-mini)",       "openai"),
        ("Mistral        (mistral-small free)",         "mistral"),
        ("xAI Grok       (grok-3-mini)",                "xai"),
        ("ZhipuAI GLM    (glm-4-flash free)",           "glm"),
        ("OpenRouter     (all providers in one)",       "openrouter"),
        ("Anthropic Claude (claude-3-5-sonnet)",        "anthropic"),
        ("Custom OpenAI-compatible endpoint",           "custom"),
    ])

    if provider == "gemini":
        print(f"  {DIM}Get API key: https://aistudio.google.com/app/apikey{RST}")
        config["OPENAI_API_URL"] = "https://generativelanguage.googleapis.com/v1beta/openai"
        config["OPENAI_API_KEY"] = ask("Gemini API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = choose("Model", [
            ("gemini-2.0-flash  (fast, stable)",           "gemini-2.0-flash"),
            ("gemini-1.5-flash  (stable)",                 "gemini-1.5-flash"),
            ("gemini-1.5-pro   (smarter, slower)",         "gemini-1.5-pro"),
        ]) or "gemini-2.0-flash"

    elif provider == "groq":
        print(f"  {DIM}Get API key: https://console.groq.com{RST}")
        config["OPENAI_API_URL"] = "https://api.groq.com/openai/v1"
        config["OPENAI_API_KEY"] = ask("Groq API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = choose("Model", [
            ("llama-3.3-70b-versatile  (best)", "llama-3.3-70b-versatile"),
            ("llama-3.1-8b-instant     (fastest)", "llama-3.1-8b-instant"),
        ]) or "llama-3.3-70b-versatile"

    elif provider == "openai":
        print(f"  {DIM}Get API key: https://platform.openai.com/api-keys{RST}")
        config["OPENAI_API_URL"] = "https://api.openai.com/v1"
        config["OPENAI_API_KEY"] = ask("OpenAI API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = choose("Model", [
            ("gpt-4o-mini  (cheap, fast)",   "gpt-4o-mini"),
            ("gpt-4o       (best quality)",  "gpt-4o"),
        ]) or "gpt-4o-mini"

    elif provider == "mistral":
        print(f"  {DIM}Get API key: https://console.mistral.ai{RST}")
        config["OPENAI_API_URL"] = "https://api.mistral.ai/v1"
        config["OPENAI_API_KEY"] = ask("Mistral API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = ask("Model", default="mistral-small-latest") or "mistral-small-latest"

    elif provider == "xai":
        print(f"  {DIM}Get API key: https://console.x.ai{RST}")
        config["OPENAI_API_URL"] = "https://api.x.ai/v1"
        config["OPENAI_API_KEY"] = ask("xAI API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = ask("Model", default="grok-3-mini") or "grok-3-mini"

    elif provider == "glm":
        print(f"  {DIM}Get API key: https://open.bigmodel.cn{RST}")
        config["OPENAI_API_URL"] = "https://open.bigmodel.cn/api/paas/v4"
        config["OPENAI_API_KEY"] = ask("GLM API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = ask("Model", default="glm-4-flash") or "glm-4-flash"

    elif provider == "openrouter":
        print(f"  {DIM}Get API key: https://openrouter.ai/keys{RST}")
        config["OPENAI_API_URL"] = "https://openrouter.ai/api/v1"
        config["OPENAI_API_KEY"] = ask("OpenRouter API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = ask("Model", default="openai/gpt-4o-mini") or ""

    elif provider == "anthropic":
        print(f"  {DIM}Get API key: https://console.anthropic.com/{RST}")
        config["OPENAI_API_URL"] = "https://api.anthropic.com/v1"
        config["OPENAI_API_KEY"] = ask("Anthropic API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = ask("Model", default="claude-3-5-sonnet-20241022") or "claude-3-5-sonnet-20241022"

    else:  # custom
        config["OPENAI_API_URL"] = ask("API base URL", default=existing.get("OPENAI_API_URL")) or ""
        config["OPENAI_API_KEY"] = ask("API Key", default=existing.get("OPENAI_API_KEY"), secret=True) or ""
        config["OPENAI_MODEL"]   = ask("Model name", default=existing.get("OPENAI_MODEL")) or ""

    ok(f"Primary model: {config['OPENAI_MODEL']}")

    # ── Fallback model ───────────────────────────────────────────────────────
    section("Fallback Providers (optional)")
    print(f"  {DIM}Used automatically if the primary model fails or hits rate limits. Press Enter to skip any.{RST}")
    _extra = [
        ("Groq",        "GROQ_API_KEY",       "https://console.groq.com"),
        ("Mistral",     "MISTRAL_API_KEY",     "https://console.mistral.ai"),
        ("xAI Grok",    "XAI_API_KEY",         "https://console.x.ai"),
        ("ZhipuAI GLM", "GLM_API_KEY",         "https://open.bigmodel.cn"),
        ("OpenRouter",  "OPENROUTER_API_KEY",  "https://openrouter.ai"),
        ("Ollama (local)", "OLLAMA_MODEL",     "model name e.g. llama3.2"),
    ]
    added = 0
    for name, key_var, hint in _extra:
        val = ask(f"{name} ({hint})", default=existing.get(key_var), optional=True, secret=(key_var != "OLLAMA_MODEL"))
        if val:
            config[key_var] = val
            added += 1
    ok(f"{added} fallback provider(s) configured" if added else "Skipped")

    # ── Web Search ───────────────────────────────────────────────────────────
    section("Web Search — Serper API (optional)")
    print(f"  {DIM}Enables real-time Google search. Free tier: https://serper.dev{RST}")
    serper = ask("Serper API Key", default=existing.get("SERPER_API_KEY"), optional=True, secret=True)
    if serper:
        config["SERPER_API_KEY"] = serper
        ok("Web search enabled")
    else:
        ok("Skipped — web search will be disabled")

    # ── Owner ID ─────────────────────────────────────────────────────────────
    section("Bot Owner Telegram ID (recommended)")
    print(f"  {DIM}Only you can run /update and admin commands. Message @userinfobot to get your ID.{RST}")
    owner = ask("Your Telegram user ID", default=existing.get("OWNER_ID"), optional=True)
    if owner:
        config["OWNER_ID"] = owner
        ok(f"Owner ID: {owner}")
    else:
        ok("Skipped — anyone can run admin commands!")

    # ── Save ─────────────────────────────────────────────────────────────────
    save_env(config)
    print(f"\n{G}✅ Config saved to .env — starting Ninoclaw...{RST}\n")
    return config


def needs_setup():
    """Returns True if .env is missing or has no valid token"""
    existing = load_existing_env()
    token = existing.get("TELEGRAM_BOT_TOKEN", "")
    return not token or token == "YOUR_BOT_TOKEN_HERE"
